import { WorkspaceRole } from '@prisma/client';

export const WorkspaceAction = {
  VIEW_WORKSPACE: 'VIEW_WORKSPACE',
  EDIT_WORKSPACE: 'EDIT_WORKSPACE',
  ARCHIVE_WORKSPACE: 'ARCHIVE_WORKSPACE',
  INVITE_MEMBER: 'INVITE_MEMBER',
  REMOVE_MEMBER: 'REMOVE_MEMBER',
  CHANGE_MEMBER_ROLE: 'CHANGE_MEMBER_ROLE',
  VIEW_MEMBERS: 'VIEW_MEMBERS',
  VIEW_DATASETS: 'VIEW_DATASETS',
  UPLOAD_DATASET: 'UPLOAD_DATASET',
  EDIT_DATASET: 'EDIT_DATASET',
  DELETE_DATASET: 'DELETE_DATASET',
  DOWNLOAD_DATASET: 'DOWNLOAD_DATASET',
  VIEW_ANALYSIS: 'VIEW_ANALYSIS',
  CREATE_ANALYSIS: 'CREATE_ANALYSIS',
  CANCEL_ANALYSIS: 'CANCEL_ANALYSIS',
  VIEW_REPORTS: 'VIEW_REPORTS',
  CREATE_REPORT: 'CREATE_REPORT',
  DELETE_REPORT: 'DELETE_REPORT',
  DOWNLOAD_REPORT: 'DOWNLOAD_REPORT',
} as const;

export type WorkspaceActionValue = (typeof WorkspaceAction)[keyof typeof WorkspaceAction];

export const WORKSPACE_ROLE_PERMISSIONS: Record<WorkspaceRole, WorkspaceActionValue[]> = {
  OWNER: [
    WorkspaceAction.VIEW_WORKSPACE,
    WorkspaceAction.EDIT_WORKSPACE,
    WorkspaceAction.ARCHIVE_WORKSPACE,
    WorkspaceAction.INVITE_MEMBER,
    WorkspaceAction.REMOVE_MEMBER,
    WorkspaceAction.CHANGE_MEMBER_ROLE,
    WorkspaceAction.VIEW_MEMBERS,
    WorkspaceAction.VIEW_DATASETS,
    WorkspaceAction.UPLOAD_DATASET,
    WorkspaceAction.EDIT_DATASET,
    WorkspaceAction.DELETE_DATASET,
    WorkspaceAction.DOWNLOAD_DATASET,
    WorkspaceAction.VIEW_ANALYSIS,
    WorkspaceAction.CREATE_ANALYSIS,
    WorkspaceAction.CANCEL_ANALYSIS,
    WorkspaceAction.VIEW_REPORTS,
    WorkspaceAction.CREATE_REPORT,
    WorkspaceAction.DELETE_REPORT,
    WorkspaceAction.DOWNLOAD_REPORT,
  ],
  ADMIN: [
    WorkspaceAction.VIEW_WORKSPACE,
    WorkspaceAction.EDIT_WORKSPACE,
    WorkspaceAction.INVITE_MEMBER,
    WorkspaceAction.REMOVE_MEMBER,
    WorkspaceAction.CHANGE_MEMBER_ROLE,
    WorkspaceAction.VIEW_MEMBERS,
    WorkspaceAction.VIEW_DATASETS,
    WorkspaceAction.UPLOAD_DATASET,
    WorkspaceAction.EDIT_DATASET,
    WorkspaceAction.DELETE_DATASET,
    WorkspaceAction.DOWNLOAD_DATASET,
    WorkspaceAction.VIEW_ANALYSIS,
    WorkspaceAction.CREATE_ANALYSIS,
    WorkspaceAction.CANCEL_ANALYSIS,
    WorkspaceAction.VIEW_REPORTS,
    WorkspaceAction.CREATE_REPORT,
    WorkspaceAction.DELETE_REPORT,
    WorkspaceAction.DOWNLOAD_REPORT,
  ],
  RESEARCHER: [
    WorkspaceAction.VIEW_WORKSPACE,
    WorkspaceAction.VIEW_MEMBERS,
    WorkspaceAction.VIEW_DATASETS,
    WorkspaceAction.UPLOAD_DATASET,
    WorkspaceAction.EDIT_DATASET,
    WorkspaceAction.DOWNLOAD_DATASET,
    WorkspaceAction.VIEW_ANALYSIS,
    WorkspaceAction.CREATE_ANALYSIS,
    WorkspaceAction.VIEW_REPORTS,
    WorkspaceAction.CREATE_REPORT,
    WorkspaceAction.DOWNLOAD_REPORT,
  ],
  VIEWER: [
    WorkspaceAction.VIEW_WORKSPACE,
    WorkspaceAction.VIEW_MEMBERS,
    WorkspaceAction.VIEW_DATASETS,
    WorkspaceAction.DOWNLOAD_DATASET,
    WorkspaceAction.VIEW_ANALYSIS,
    WorkspaceAction.VIEW_REPORTS,
    WorkspaceAction.DOWNLOAD_REPORT,
  ],
};
