import express from 'express';
import path from 'node:path';
import cors from 'cors';
import morgan from 'morgan';
import authRoutes from './routes/auth.js';
import healthDataRoutes from './routes/health-data.js';
import analysisJobsRoutes from './modules/analysis-jobs/analysis-jobs.module.js';
import profileRoutes from './modules/profile/profile.module.js';
import notificationRoutes from './routes/notifications.js';
import pipelineRoutes from './routes/pipelines.js';
import adminRoutes from './routes/admin.js';
import adminGovernanceRoutes from './routes/admin-governance.js';
import adminPolicyRoutes from './routes/admin-policy.js';
import systemMonitoringRealtimeRoutes from './modules/system-monitoring-realtime/system-monitoring-realtime.module.js';
import systemMonitoringRoutes from './modules/system-monitoring/system-monitoring.module.js';
import userRoutes from './routes/users.js';
import workspaceRoutes from './routes/workspaces.js';
import researcherApplicationsRoutes from './routes/researcher-applications.js';
import supportRoutes from './routes/support.js';
import dataDepositRoutes from './routes/data-deposit.js';
import cohortsRoutes from './routes/cohorts.js';
import statisticsRoutes from './modules/statistics/statistics.module.js';
import mlRoutes from './modules/ml/ml.module.js';
import survivalRoutes from './modules/survival/survival.module.js';
import genomicsRoutes from './modules/genomics/genomics.module.js';
import experimentTrackingRoutes from './modules/experiment-tracking/experiment-tracking.module.js';
import communicationRoutes from './modules/communication/communication.module.js';
import messagesRoutes from './modules/communication/messages.module.js';
import { errorHandler } from './middleware/error-handler.js';
import { requestId } from './middleware/request-id.js';
import { rateLimit } from './middleware/rate-limit.js';
import { securityHeaders } from './middleware/security-headers.js';
import opsRoutes from './routes/ops.js';
import sdohRoutes from './routes/sdoh.js';
import researchLifecycleRoutes from './routes/research-lifecycle.js';
import databaseRoutes from './routes/database.js';
import datasetRegistryRoutes from './routes/dataset-registry.js';
import dataPreparationRoutes from './routes/data-preparation.js';
import workspaceZipRoutes from './routes/workspaceZip.routes.js';
import platformCrossLayerRoutes from './routes/platform-cross-layer.js';
import governanceCrossLayerRoutes from './routes/governance-cross-layer.js';
import systemServicesCrossLayerRoutes from './routes/system-services-cross-layer.js';
import adminCommunicationRoutes from './routes/admin-communication.js';
import userCommunicationRoutes from './routes/user-communication.js';

export function createApp() {
  const app = express();

  app.use(cors({ origin: true, credentials: true }));
  app.use(morgan('dev'));
  app.use(express.json());
  app.use('/uploads', express.static(path.resolve(process.cwd(), 'uploads')));

  app.get('/health', (_req, res) => res.json({ status: 'ok', requestId: res.locals.requestId }));
  app.use('/api/v1/ops', opsRoutes);
  app.use('/api/sdoh', sdohRoutes);
  app.use('/api/v1/sdoh', sdohRoutes);
  app.use('/api/sdoh-intelligence', sdohRoutes);
  app.use('/api/research-lifecycle', researchLifecycleRoutes);
  app.use('/api/v1/research-lifecycle', researchLifecycleRoutes);
  app.use('/api/database', databaseRoutes);
  app.use('/api/v1/database', databaseRoutes);
  app.use('/api/data-preparation', dataPreparationRoutes);
  app.use('/api/v1/data-preparation', dataPreparationRoutes);
  app.use('/api/workspace-zip', workspaceZipRoutes);
  app.use('/api/v1/workspace-zip', workspaceZipRoutes);
  app.use('/api/platform', platformCrossLayerRoutes);
  app.use('/api/v1/platform', platformCrossLayerRoutes);
  app.use('/api/governance', governanceCrossLayerRoutes);
  app.use('/api/v1/governance', governanceCrossLayerRoutes);
  app.use('/api/system', systemServicesCrossLayerRoutes);
  app.use('/api/v1/system', systemServicesCrossLayerRoutes);
  app.use('/api/dataset-registry', datasetRegistryRoutes);
  app.use('/api/v1/dataset-registry', datasetRegistryRoutes);
  app.use('/api/auth', authRoutes);
  app.use('/api/v1/auth', authRoutes);
  app.use('/api/analysis/jobs', analysisJobsRoutes);
  app.use('/api/analysis-jobs', analysisJobsRoutes);
  app.use('/api/v1/analysis-jobs', analysisJobsRoutes);
  app.use('/api/profile', profileRoutes);
  app.use('/api/v1/profile', profileRoutes);
  app.use('/api/notifications', notificationRoutes);
  app.use('/api/v1/notifications', notificationRoutes);
  app.use('/api/pipeline-runs', pipelineRoutes);
  app.use('/api/v1/pipeline-runs', pipelineRoutes);
  app.use('/api/v1/admin', adminRoutes);
  app.use('/api/v1/admin/communication', adminCommunicationRoutes);
  app.use('/api/v1/user-communication', userCommunicationRoutes);
  app.use('/api/v1/admin-governance', adminGovernanceRoutes);
  app.use('/api/v1/admin-policy', adminPolicyRoutes);
  app.use('/api/v1/system-monitoring', systemMonitoringRealtimeRoutes);
  app.use('/api/v1/system-monitoring', systemMonitoringRoutes);
  app.use('/api/v1/users', userRoutes);
  app.use('/api/workspaces', workspaceRoutes);
  app.use('/api/v1/workspaces', workspaceRoutes);
  app.use('/api/health-data', healthDataRoutes);
  app.use('/api/v1/admin/researcher-applications', researcherApplicationsRoutes);
  app.use('/api/support', supportRoutes);
  app.use('/api/v1/support', supportRoutes);
  app.use('/api/v1/datasets/deposit', dataDepositRoutes);
  app.use('/api/v1/cohorts', cohortsRoutes);
  app.use('/api/v1/statistics', statisticsRoutes);
  app.use('/api/v1/ml', mlRoutes);
  app.use('/api/v1/survival', survivalRoutes);
  app.use('/api/v1/genomics', genomicsRoutes);
  app.use('/api/v1/experiments', experimentTrackingRoutes);
  app.use('/api/v1/communication', communicationRoutes);
  app.use('/api/messages', messagesRoutes);
  app.use('/api/v1/messages', messagesRoutes);

  app.use(errorHandler);
  return app;
}
