import fs from 'node:fs/promises';
import path from 'node:path';
import type { Request } from 'express';
import { prisma } from '../../db/prisma.js';

export type SdohFeatureFlagKey =
  | 'causal_module'
  | 'counterfactual_simulator'
  | 'policy_simulator'
  | 'publication_suite'
  | 'gis'
  | 'survival';

type CurrentActor = {
  userId: string;
  role: string;
};

const flagDefinitions: Array<{ key: SdohFeatureFlagKey; packKey: string; description: string }> = [
  { key: 'causal_module', packKey: 'sdoh.causal.enabled', description: 'Enable causal inference, PSM, IPTW, and DiD routes.' },
  { key: 'counterfactual_simulator', packKey: 'sdoh.counterfactual.enabled', description: 'Enable counterfactual intervention simulation.' },
  { key: 'policy_simulator', packKey: 'sdoh.policy.enabled', description: 'Enable policy simulation outputs.' },
  { key: 'publication_suite', packKey: 'sdoh.publication.enabled', description: 'Enable publication analytics and study-pack outputs.' },
  { key: 'gis', packKey: 'sdoh.gis.enabled', description: 'Enable geographic intelligence.' },
  { key: 'survival', packKey: 'sdoh.survival.enabled', description: 'Enable survival and Cox analysis outputs.' },
];

const exportDir = path.resolve(process.cwd(), 'storage', 'sdoh-exports');

function escapeCsv(value: unknown) {
  const text = value === null || value === undefined ? '' : String(value);
  return /[",\n\r]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

function flattenRows(rows: Array<Record<string, unknown>>) {
  const safeRows = rows.length ? rows : [{ message: 'No rows supplied' }];
  const columns = Array.from(new Set(safeRows.flatMap((row) => Object.keys(row))));
  return { rows: safeRows, columns };
}

function renderCsv(rows: Array<Record<string, unknown>>) {
  const flattened = flattenRows(rows);
  return [
    flattened.columns.map(escapeCsv).join(','),
    ...flattened.rows.map((row) => flattened.columns.map((column) => escapeCsv(row[column])).join(',')),
  ].join('\n');
}

function renderSpreadsheetHtml(title: string, rows: Array<Record<string, unknown>>) {
  const flattened = flattenRows(rows);
  const header = flattened.columns.map((column) => `<th>${escapeCsv(column)}</th>`).join('');
  const body = flattened.rows
    .map((row) => `<tr>${flattened.columns.map((column) => `<td>${escapeCsv(row[column])}</td>`).join('')}</tr>`)
    .join('');
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title></head><body><table><caption>${title}</caption><thead><tr>${header}</tr></thead><tbody>${body}</tbody></table></body></html>`;
}

function escapePdf(value: unknown) {
  return String(value ?? '').replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function renderPdf(title: string, rows: Array<Record<string, unknown>>) {
  const flattened = flattenRows(rows);
  const lines = [
    title,
    'Generated by DataNotch SDOH Publication Analytics',
    '',
    flattened.columns.slice(0, 6).join(' | '),
    ...flattened.rows.slice(0, 35).map((row) => flattened.columns.slice(0, 6).map((column) => String(row[column] ?? '').slice(0, 24)).join(' | ')),
  ];
  const text = lines.map((line, index) => `BT /F1 9 Tf 40 ${760 - index * 18} Td (${escapePdf(line)}) Tj ET`).join('\n');
  const stream = `<< /Length ${text.length} >>\nstream\n${text}\nendstream`;
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj ${stream} endobj`,
  ];
  let offset = '%PDF-1.4\n'.length;
  const xref = ['0000000000 65535 f '];
  const body = objects
    .map((object) => {
      xref.push(`${String(offset).padStart(10, '0')} 00000 n `);
      offset += object.length + 1;
      return object;
    })
    .join('\n');
  const xrefStart = offset;
  return `%PDF-1.4\n${body}\nxref\n0 ${objects.length + 1}\n${xref.join('\n')}\ntrailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;
}

export class SdohGovernanceService {
  private initialized = false;

  async ensureReady() {
    if (this.initialized) return;
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS sdoh_feature_flags (
        key TEXT PRIMARY KEY,
        enabled BOOLEAN NOT NULL DEFAULT TRUE,
        description TEXT,
        pack_key TEXT,
        updated_by TEXT,
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS sdoh_audit_logs (
        id TEXT PRIMARY KEY,
        user_id TEXT,
        role TEXT,
        action TEXT NOT NULL,
        resource_type TEXT NOT NULL,
        resource_id TEXT,
        ip_address TEXT,
        metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS sdoh_datasets (
        id TEXT PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        source_type TEXT NOT NULL DEFAULT 'demo_cohort',
        row_count INTEGER NOT NULL DEFAULT 0,
        column_count INTEGER NOT NULL DEFAULT 0,
        schema_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_by TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS sdoh_exports (
        id TEXT PRIMARY KEY,
        export_type TEXT NOT NULL,
        filename TEXT NOT NULL,
        path TEXT NOT NULL,
        created_by TEXT,
        metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    await prisma.$executeRawUnsafe(`
      CREATE TABLE IF NOT EXISTS sdoh_publication_outputs (
        id TEXT PRIMARY KEY,
        output_type TEXT NOT NULL,
        title TEXT NOT NULL,
        content_json JSONB NOT NULL DEFAULT '{}'::jsonb,
        created_by TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);
    for (const flag of flagDefinitions) {
      await prisma.$executeRawUnsafe(
        `
          INSERT INTO sdoh_feature_flags (key, enabled, description, pack_key, updated_by)
          VALUES ($1, TRUE, $2, $3, 'system')
          ON CONFLICT (key) DO NOTHING
        `,
        flag.key,
        flag.description,
        flag.packKey,
      );
    }
    await fs.mkdir(exportDir, { recursive: true });
    this.initialized = true;
  }

  async listFeatureFlags() {
    await this.ensureReady();
    const rows = await prisma.$queryRawUnsafe<Array<{ key: SdohFeatureFlagKey; enabled: boolean }>>(
      'SELECT key, enabled FROM sdoh_feature_flags ORDER BY key',
    );
    return Object.fromEntries(rows.map((row) => [row.key, row.enabled])) as Record<SdohFeatureFlagKey, boolean>;
  }

  async setFeatureFlag(key: SdohFeatureFlagKey, enabled: boolean, actor: CurrentActor, req?: Request) {
    await this.ensureReady();
    await prisma.$executeRawUnsafe(
      `
        INSERT INTO sdoh_feature_flags (key, enabled, updated_by, updated_at)
        VALUES ($1, $2, $3, now())
        ON CONFLICT (key) DO UPDATE SET enabled = EXCLUDED.enabled, updated_by = EXCLUDED.updated_by, updated_at = now()
      `,
      key,
      enabled,
      actor.userId,
    );
    await this.recordAudit(actor, 'feature_flag.update', 'feature_flag', key, { enabled }, req);
    return this.listFeatureFlags();
  }

  async registerDemoDataset(profile: { rows: number; columns: string[] }, actor: CurrentActor = { userId: 'system', role: 'system' }) {
    await this.ensureReady();
    await prisma.$executeRawUnsafe(
      `
        INSERT INTO sdoh_datasets (id, name, description, source_type, row_count, column_count, schema_json, created_by)
        VALUES ('demo-sdoh', 'Demo SDOH Cohort', 'Seeded SDOH clinical outcomes and population health cohort.', 'demo_cohort', $1, $2, $3::jsonb, $4)
        ON CONFLICT (id) DO UPDATE SET row_count = EXCLUDED.row_count, column_count = EXCLUDED.column_count, schema_json = EXCLUDED.schema_json
      `,
      profile.rows,
      profile.columns.length,
      JSON.stringify({ columns: profile.columns }),
      actor.userId,
    );
  }

  async listDatasets() {
    await this.ensureReady();
    return prisma.$queryRawUnsafe<Array<Record<string, unknown>>>('SELECT * FROM sdoh_datasets ORDER BY created_at DESC LIMIT 100');
  }

  async createExport(format: string, title: string, rows: Array<Record<string, unknown>>, actor: CurrentActor, req?: Request) {
    await this.ensureReady();
    const normalized = format.toLowerCase();
    if (!['csv', 'xlsx', 'pdf'].includes(normalized)) {
      throw new Error('Unsupported export format. Use csv, xlsx, or pdf.');
    }
    const id = `sdoh-export-${Date.now()}`;
    const filename = `${id}.${normalized}`;
    const filePath = path.join(exportDir, filename);
    const content =
      normalized === 'csv'
        ? renderCsv(rows)
        : normalized === 'xlsx'
          ? renderSpreadsheetHtml(title, rows)
          : renderPdf(title, rows);
    await fs.writeFile(filePath, content, 'utf8');
    await prisma.$executeRawUnsafe(
      `
        INSERT INTO sdoh_exports (id, export_type, filename, path, created_by, metadata_json)
        VALUES ($1, $2, $3, $4, $5, $6::jsonb)
      `,
      id,
      normalized,
      filename,
      filePath,
      actor.userId,
      JSON.stringify({ title, rows: rows.length }),
    );
    await this.recordAudit(actor, 'export.create', 'sdoh_export', id, { format: normalized, filename }, req);
    return { id, filename, filePath, content, format: normalized };
  }

  async listExports() {
    await this.ensureReady();
    return prisma.$queryRawUnsafe<Array<Record<string, unknown>>>('SELECT * FROM sdoh_exports ORDER BY created_at DESC LIMIT 100');
  }

  async getExport(id: string) {
    await this.ensureReady();
    const rows = await prisma.$queryRawUnsafe<Array<{ filename: string; path: string; export_type: string }>>(
      'SELECT filename, path, export_type FROM sdoh_exports WHERE id = $1 LIMIT 1',
      id,
    );
    return rows[0] ?? null;
  }

  async recordPublicationOutput(outputType: string, title: string, content: Record<string, unknown>, actor: CurrentActor) {
    await this.ensureReady();
    const id = `sdoh-publication-${Date.now()}-${Math.round(Math.random() * 1000)}`;
    await prisma.$executeRawUnsafe(
      `
        INSERT INTO sdoh_publication_outputs (id, output_type, title, content_json, created_by)
        VALUES ($1, $2, $3, $4::jsonb, $5)
      `,
      id,
      outputType,
      title,
      JSON.stringify(content),
      actor.userId,
    );
    return { id, outputType, title };
  }

  async listPublicationOutputs() {
    await this.ensureReady();
    return prisma.$queryRawUnsafe<Array<Record<string, unknown>>>(
      'SELECT * FROM sdoh_publication_outputs ORDER BY created_at DESC LIMIT 100',
    );
  }

  async recordAudit(actor: CurrentActor, action: string, resourceType: string, resourceId?: string, metadata: Record<string, unknown> = {}, req?: Request) {
    await this.ensureReady();
    const id = `sdoh-audit-${Date.now()}-${Math.round(Math.random() * 1000)}`;
    await prisma.$executeRawUnsafe(
      `
        INSERT INTO sdoh_audit_logs (id, user_id, role, action, resource_type, resource_id, ip_address, metadata_json)
        VALUES ($1, $2, $3, $4, $5, $6, $7, $8::jsonb)
      `,
      id,
      actor.userId,
      actor.role,
      action,
      resourceType,
      resourceId ?? null,
      req?.ip ?? null,
      JSON.stringify(metadata),
    );
    return { id, action, resourceType };
  }

  async listAuditLogs() {
    await this.ensureReady();
    return prisma.$queryRawUnsafe<Array<Record<string, unknown>>>('SELECT * FROM sdoh_audit_logs ORDER BY created_at DESC LIMIT 200');
  }
}

export const sdohGovernanceService = new SdohGovernanceService();
