export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN',
  REVIEWER = 'REVIEWER',
}

export enum AccountStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED_2FA_PENDING = 'APPROVED_2FA_PENDING',
  ACTIVE = 'ACTIVE',
  REJECTED = 'REJECTED',
  SUSPENDED = 'SUSPENDED',
}

export enum ResearcherType {
  GENERAL_RESEARCHER = 'GENERAL_RESEARCHER',
  STUDENT_RESEARCHER = 'STUDENT_RESEARCHER',
  CLINICAL_RESEARCHER = 'CLINICAL_RESEARCHER',
  EXTERNAL_COLLABORATOR = 'EXTERNAL_COLLABORATOR',
}

export enum ApplicationReviewStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEEDS_MORE_INFO = 'NEEDS_MORE_INFO',
}

export enum ApplicationReviewDecision {
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
}
